= Evaluation of StarFive VisionFive SBC
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:example-caption!:
:table-caption!:
:prewrap!:
:imagesdir: docs/img
:toc:
:toc-placement!:
:sectnums:
:sectanchors:
:sectlinks:
:PROJECT_NAME: visionfive-debos
:PROJECT_URL: https://github.com/cristicc/{PROJECT_NAME}
:PROJECT_DIR: ${HOME}/{PROJECT_NAME}
:OUTPUT_DIR: {PROJECT_DIR}/build

toc::[]

[IMPORTANT]
This is currently a work in progress.

== Intro

This is an experimental Debian based OS and application for the VisionFive SBC
from StarFive <<RefQuickStartQuide>>.

The main purpose of the project is to evaluate the mainline kernel support and
to find areas of further improvements.

== Boot process

ifdef::env-github[]
image::visionfive-boot-process.svg[]
endif::[]

ifndef::env-github[]
[ditaa]
----
/-----------\
|           |
|  BootROM  |
|      cCCC |
\-----+-----/
      |
      | Select boot source
      | ٭ UART ‑ Load a limited size binary into the on‑chip RAM and execute it
      |          (for upgrading firmware)
      | ٭ QSPI ‑ Automatically load the 32K Bootloader from 0x0 (NOR Flash)
      |          to 0x18000000 (RAM); jump to it for execution
      v
+-----------\      +----------------------+
|           |      | {d}                  |
| BootLoader|<--=--+ bootloader‑٭.bin.out |
|      cCDF |      |                 cFA7 |
\-----+-----+      +----------------------+
      |
      | Read DDRInit from 0x10000 (NOR Flash) to 0x18080000 (RAM);
      | jump to it for execution
      v
+-----------\      +----------------------+
|           |      | {d}                  |
|  DDRInit  |<--=--+  ddrinit‑٭.bin.out   |
|      cCDF |      |                 cFA7 |
\-----+-----+      +----------------------+
      |
      | Initialize DDR; read fw_payload (OpenSBI + U‑Boot) from 0x40000
      | (NOR Flash) to 0x80000000 (DDR); jump to it to execute the OpenSBI
      v
+-----------\      +----------------------+
|           |      | {d}                  |
|  OpenSBI  |<--=--+  fw_payload.bin.out  |
|      cCDF |      |                 cFA7 |
\-----+-----+      +----------------------+
      |
      | Provide basic system calls for Linux; switch the mode from M to S;
      | jump to 0x80020000 (DDR) to execute U‑Boot
      |
      v            +-----------------+
+-----------+      | {d}             |
|           |      |  ٭ u‑boot.bin   |
|  U‑Boot   |<--=--+  ٭ u‑boot.dtb   |
|      cGRE |      |  ٭ uEnv.txt     |
+-----+-----+      |            cFA7 |
      |            +-----------------+
      |
      | Works in S mode; contains basic file system and peripheral drivers
      | (GMAC, UART, QSPI, USB, SDIO, etc.); load GRUB 2 UEFI playload from
      | SDIO to 0xa0000000 and execute it via bootefi command
      v
+-----------+      +--------------------+
|           |      | {d}                |
|  GRUB 2   |<--=--+ ٭ grubriscv64.efi  |
|      cGRE |      | ٭ grub.cfg         |
+-----+-----+      |               cFA7 |
      |            +--------------------+
      |
      | Select one of the menu entries in grub.cfg and boot a Linux kernel
      | image, providing also a DT blob and initramfs
      |
      v            +------------------------------------+
+------------+     | {d}                                |
|            |     | ٭ vmlinuz‑6.0.0‑visionfive         |
|Linux Kernel|<--=-+ ٭ jh7100‑starfive‑visionfive‑v1.dtb|
|       cD54 |     | ٭ initrd.img‑6.0.0‑visionfive      |
+-----+------+     |                                cFA7|
      |            +------------------------------------+
      |
      | Initialize hardware, load drivers and mount root filesystem;
      | launch user space init process
      v
+-----------+      +--------------------+
|           |      | {d}                |
|  RootFS   |<--=--+ debian‑riscv64.img |
|      cPNK |      |               cFA7 |
+-----------+      +--------------------+
----
endif::[]


== Hardware connectivity

=== Terminal access via serial port

Connect one of the USB to serial adapters to the 40-Pin GPIO header (PIN6-GND,
PIN10-RXD, PIN8-TXD):

* FTDI TTL-232R-3V3 Cable (BLACK-GND, ORANGE-TXD, YELLOW-RXD)
* PL2303TA TTL-232R-3V3 Cable (BLACK-GND, GREEN-TXD, WHITE-RXD)
* PL2303HX TTL-232R-3V3 Cable (BLUE-GND, RED-TXD, GREEN-RXD)

Assuming the serial adapter on the host system is available under `ttyUSB0`,
open a serial console using either `screen` or `minicom` utilities:

[source,sh]
$ screen /dev/ttyUSB0 115200
$ minicom -D /dev/ttyUSB0 -b 115200 -c on


== Setup development environment

=== Create Docker image

Use the command below to build a Docker image containing a toolchain to be used
for building the Linux kernel for the RISC-V architecture. The image will be
named `visionfive/cross`.

[source,sh]
----
$ docker/docker.sh [-p WORK_DIR] build
[...]
Successfully built 801f692ad877
Successfully tagged visionfive/cross:latest

$ docker images visionfive/cross
REPOSITORY         TAG       IMAGE ID       CREATED         SIZE
visionfive/cross   latest    801f692ad877   2 minutes ago   626MB
----

The optional `-p` or `--project-dir` parameter allows to map a path in the host
system to the guest environment. By default it is the current project root
directory.


=== Run Docker container

The `docker/docker.sh` script above can be used to quickly run a build container
or execute commands inside the development environment:

[source,sh]
----
$ docker/docker.sh --help
Usage: docker.sh [OPTION]... COMMAND
Helper script to automate Docker container creation for building VisionFive sources.

Options:
  -h, --help        Display this help text and exit

  -p, --project_dir DIR
                    Set project directory to a custom location.

Commands:
  build             Build docker image
  run               Run docker container
  exec [COMMAND]    Execute a command in the container
  stop              Stop docker container
  status            Show docker container status
----

Pass the `run` command to instantiate a container named `visionfive-build` and
provide an interactive console terminal. Note the project content is made
available in the container under the path specified on image creation.

[source,sh]
----
$ docker/docker.sh run
visionfive-build:~/visionfive-debos$ ls
LICENSE  README.adoc  debos  docker  docs  tools
----

You may check the container status from a host console terminal:

[source,sh]
----
$ docker/docker.sh status
'visionfive-build' container status: running

$ docker ps
CONTAINER ID   IMAGE              COMMAND       CREATED          STATUS          PORTS     NAMES
f5524864bb34   visionfive/cross   "/bin/bash"   11 minutes ago   Up 11 minutes             visionfive-build
----


== Build Linux kernel

The build environment provides the `kmake` alias which can be used as a helper
to configure and build the kernel sources:

[source,sh]
----
visionfive-build:~/visionfive-debos$ alias kmake
alias kmake='make -j 9 O=build ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- LOCALVERSION=""'
----

=== Clone linux repositories

Let's create the `work` directory for cloning any git repositories required by
the project:

[source,sh]
----
visionfive-build:~/visionfive-debos$ mkdir work && cd work
visionfive-build:~/visionfive-debos/work$
----

Now clone `linux` Git repository and, optionally, also checkout `linux-next` in
a separate git working tree:

[source,sh]
----
visionfive-build:~/visionfive-debos/work$ git clone -o linux git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
visionfive-build:~/visionfive-debos/work$ cd linux
# Skip the commands below if linux-next is not of interest.
visionfive-build:~/visionfive-debos/work/linux$ git remote add linux-next git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
visionfive-build:~/visionfive-debos/work/linux$ git fetch linux-next
visionfive-build:~/visionfive-debos/work/linux$ git worktree add --checkout -b linux-next ../linux-next next-20221028
----

It might be useful to have quick access to the downstream kernel repository, as
well:

[source,sh]
----
visionfive-build:~/visionfive-debos/work/linux$ git remote add starfive git@github.com:starfive-tech/linux.git
visionfive-build:~/visionfive-debos/work/linux$ git fetch starfive
visionfive-build:~/visionfive-debos/work/linux$ git worktree add --checkout -b linux-starfive ../linux-starfive starfive/visionfive
----


=== Patch sources

To enable support for the StarFive VisionFive SBC in mainline kernel, it's
necessary to apply a few patches. Note a patch series has been already submitted
upstream and should be merged soon:

https://lore.kernel.org/all/20221017210542.979051-1-cristian.ciocaltea@collabora.com/

The patch series can be easily downloaded and applied using the `b4` utility:

[source,sh]
----
visionfive-build:~/visionfive-debos/work/linux$ b4 am -l 20221017210542.979051-1-cristian.ciocaltea@collabora.com
visionfive-build:~/visionfive-debos/work/linux$ git am ./v4_20221018_cristian_ciocaltea_enable_initial_support_for_starfive_visionfive_v1_sbc.mbx
----

Alternatively, the patches are also stored in this project repository, so one
may apply them by running:

[source,sh]
----
visionfive-build:~/visionfive-debos/work/linux$ git am --empty=drop ../../linux/patches/*.patch
----


=== Configure target board

While still in the `work/linux` folder, let's create a subfolder `build` for
configuring and compiling the kernel using the already provided `defconfig`.
This is a minimal configuration to get StartFive VisionFive SBC booting with
the mainline kernel.

[TIP]
The `kmake` alias already passes the name of the `build` subfolder to `make`
via `O=build` argument.

[source,sh]
----
visionfive-build:~/visionfive-debos/work/linux$ mkdir -p build
visionfive-build:~/visionfive-debos/work/linux$ cp ../../linux/visionfive_defconfig build/.config
visionfive-build:~/visionfive-debos/work/linux$ kmake olddefconfig
----

Optionally adjust the configuration by calling `kmake menuconfig`.


=== Build kernel image and device tree blob

Having `.config` file ready, it's time to start compiling the sources.

[source,sh]
----
visionfive-build:~/visionfive-debos/work/linux$ kmake
[...]
  DTC     arch/riscv/boot/dts/starfive/jh7100-starfive-visionfive-v1.dtb
[...]
  LD      vmlinux
  NM      System.map
  SORTTAB vmlinux
  OBJCOPY arch/riscv/boot/Image
  GZIP    arch/riscv/boot/Image.gz
  Kernel: arch/riscv/boot/Image.gz is ready
make[1]: Leaving directory '~/visionfive-debos/work/linux/build'
----

[TIP]
--
By default, `kmake` is configured to use all available processing units, plus
one. To set it to a custom value, e.g. `2`, it's necessary to update
`docker/Dockerfile` and rebuild the container:

[source,sh]
----
$ sed -i 's/$(($(nproc)+1))/2/' docker/Dockerfile
$ docker/docker.sh build
----
--

Generate Debian packages and, optionally, install the kernel image and DTB to
`build/dist` folder:

[source,sh]
----
visionfive-build:~/visionfive-debos/work/linux$ kmake bindeb-pkg
visionfive-build:~/visionfive-debos/work/linux$ ls -1 *.deb
linux-image-6.1.0-rc1-visionfive_6.1.0-rc1-visionfive-1_riscv64.deb
linux-libc-dev_6.1.0-rc1-visionfive-1_riscv64.deb

# Local install (optional)
visionfive-build:~/visionfive-debos/work/linux$ mkdir build/dist
visionfive-build:~/visionfive-debos/work/linux$ kmake INSTALL_PATH=dist zinstall dtbs_install
----


== Build GRUB2 for RISCV64 architecture

=== Clone GRUB2 repositories

This can be done either from a console on the host system or on the build
container:

[source,sh]
----
$ cd work/
$ git clone git://git.savannah.gnu.org/grub.git
# TODO: Drop the commands below when upstream support is complete
$ cd grub
$ git remote add tekkamanninja https://github.com/tekkamanninja/grub.git
$ git fetch tekkamanninja
$ git switch -C riscv_devel tekkamanninja/riscv_devel_Nikita_V3
----

=== Build GRUB2 EFI image

Run the following commands from the build container:

[source,sh]
----
visionfive-build:~$ cd visionfive-debos/work/grub
visionfive-build:~/visionfive-debos/work/grub$ ../../grub/build.sh
./bin/grub-mkimage: info: reading ~/visionfive-debos/grub/default.cfg.
./bin/grub-mkimage: info: kernel_img=0x7f1179bd4010, kernel_size=0x1a000.
./bin/grub-mkimage: info: the core size is 0x2e75f0.
./bin/grub-mkimage: info: writing 0x2ea000 bytes.
Successfully built GRUB2 image: ~/visionfive-debos/grub/dist/grubriscv64.efi
----


[bibliography]
== References
* [[[RefQuickStartQuide,1]]] https://doc-en.rvspace.org/VisionFive/Quick_Start_Guide/VisionFive_QSG/specifications.html
* [[[RefStarfiveRepo,2]]] https://github.com/starfive-tech/VisionFive
